### ISSUE TITLE
How can I use the 'NCNet' only when I run the 'visualize_matches.py'?

### ISSUE THREAD

**Issue by BruceWANGDi** [GrumpyZhou/patch2pix#1]
Hi, Could you give me any advice? I want to output some results like the results you illustrated in your paper(Figure7). How can I modify the code in 'visualize_matches.py' to get the outcome like that?

**Comment by GrumpyZhou** [comment]
Hi @BruceWANGDi ,

Do you mean how to plot results on Aachen benchmark? I was using the visualization tools provided by HLoc, you can find the implementation in [visualization.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/visualization.py).
