### ISSUE TITLE
What's the meaning of R and t in megadepth_pairs.ov0.35_imrat1.5.pair500.excl_test.npy when computing F matrix?

### ISSUE THREAD

**Issue by HUSTNO1WXY** [GrumpyZhou/patch2pix#12]
Notice that there are R and t as inputs when computing F matrix which is used to generate geometric loss, but from my knowledge each image will have a R matrix and t  matrix which are extracted from absolute pose. R and t here are elements from relative pose?

**Comment by GrumpyZhou** [comment]
@HUSTNO1WXY yes, it is the relative pose between the two images in a pair.
