### ISSUE TITLE
Checkpoint Path Invalid

### ISSUE THREAD

**Issue by ashish-kubade** [GrumpyZhou/patch2pix#15]
Hi @GrumpyZhou , Greetings!!
Thanks for the amazing work on patch2pix.

I was trying out patch2pix, however, the checkpoint paths seem invalid. Could you please confirm if the checkpoints have been migrated?

-Thanks

**Comment by GrumpyZhou** [comment]
Thanks for pointing this out. The models are uploaded here now [patch2pix pretrained](https://drive.google.com/drive/folders/1OAyDJz3LC38macJXQjmXgvA58zxLlDir?usp=drive_link) . I will update the readme.
