### ISSUE TITLE
data_pair url can't be found

### ISSUE THREAD

**Issue by Snake-1** [GrumpyZhou/patch2pix#16]
Hello Authors,
I am getting Not Found error when I am using the url in data_pair to download traing data.
The url is https://vision.in.tum.de/webshare/u/zhouq/patch2pix/data_pairs/megadepth_pairs.ov0.35_imrat1.5.pair500.excl_test.npy.
Has anyone faced this issue?

**Comment by GrumpyZhou** [comment]
Hi @Snake-1 , thanks for pointing this out. I have updated the download script.
