### ISSUE TITLE
Quantization Code

### ISSUE THREAD

**Issue by QsingHuan** [GrumpyZhou/patch2pix#2]
Dear Author,
You've mentioned that to evaluate this method on Aachen Day-Night Benchmark, you did quantization for the matches. Will you release the code for the quantization part?

**Comment by GrumpyZhou** [comment]
Hi @QsingHuan, 

I will release the code for all evaluations in another repository [image-matching-toolbox](https://github.com/GrumpyZhou/image-matching-toolbox), to keep this repo clean. I plan to push the code for aachen benchmark next week in that repo.
