### ISSUE TITLE
Can the pre-trained model be used both indoor and outdoor ?

### ISSUE THREAD

**Issue by noone-code** [GrumpyZhou/patch2pix#3]
Thank you for sharing your brilliant work.

I have a little question.

Can the pre-trained `patch2pix_pretrained.pth` model be used both indoor and outdoor ?

**Comment by GrumpyZhou** [comment]
Hi, 

Yes you can used it for both indoor and outdoors, as we showed in the paper.

**Comment by noone-code** [comment]
@GrumpyZhou Thanks for your reply 😊 .
