### ISSUE TITLE
Access to data_pairs/prep_megadepth_training_pairs.ipynb

### ISSUE THREAD

**Issue by cv4aec** [GrumpyZhou/patch2pix#4]
Hi,

This is really a nice work. 

I am trying to reproduce the results in your paper. 

However, I couldn't find [data_pairs/prep_megadepth_training_pairs.ipynb](https://github.com/GrumpyZhou/patch2pix/blob/main/data_pairs/prep_megadepth_training_pairs.ipynb) and also don't have access to the link.

Could you upload the ipynb to the repo please?

Thanks.

**Comment by GrumpyZhou** [comment]
Hi,

Thanks for the remind. I didn't notice that. Now it's uploaded ;)
